import pandas as pd
import pickle

# Cols should be generated by setting "--preselect-features" to true and running the whole pipeline. You can pause the pipeline after reference cols are set and dump those.
with open("cols.pkl", "rb") as f:
    cols = pickle.load(f)

# Continuous features are aggregated using 6 different aggregate functions (if they apply), we will combine them.
# We consider the onehot categorical counts of diagnoses, procedures, cpt sections, and medications (ref CATEGORICAL_COL_REGEX) as separate features.
# Race, however will be combined (basically everything that's associated with cols_to_onehot). The rest are binary (e.g. ethnicity) so aren't inflated.
unique_features = (
    cols.str.replace(".*_indicator", "indicator", regex=True)
    .str.replace("RACE.*", "RACE", regex=True)
    # tobacco/smoking/allergen aren't currenly in the intersection of features for all 3 cohorts, i've included it here just in case
    .str.replace(".*TOBACCO_USER.*", "TOBACCO_USER", regex=True)
    .str.replace(".*SMOKING_TOB_STATUS.*", "SMOKING_TOB_STATUS", regex=True)
    .str.replace(".*ALLERGEN_ID.*", "ALLERGEN_ID", regex=True)
    .str.replace("_(mean|min|max|std|skew|len)", "", regex=True)
    .unique()
)

with open("unique_cols.pkl", "wb") as f:
    pickle.dump(unique_features, f)
